version: '3.1'

services:

  mysql:
    image: mysql
    restart: always
    ports:
        - "${MYSQL_PORT}:3306"
    build:
        context: ./mysql
        args:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  stomp:
    image: itzg/rabbitmq-stomp
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"

  redis:
    image: redis:5.0.1-alpine
    restart: always
    ports:
      - "6379:6379"